services:
  - type: web
    name: hyperemail
    env: node
    buildCommand: npm install
    startCommand: node gouvernement-scraper.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_SECURE
        value: "0"
      - key: SENDER_NAME
        value: France DÃ©mocratie
      - key: PORT
        value: 3001
      - key: API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: true
    plan: free
    healthCheckPath: /health
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1